### ISSUE TITLE
Revise load balancer/ingress docs layout

### ISSUE THREAD

**Issue by superseb** [rancher/docs#1649]
Based on what we have today, we have Load Balancers and Ingress section where Load Balancers describe Layer 4 and Layer 7 load balancers, and Ingress where we have a guide to create Ingresses (but dont describe ingress controllers cause that is covered in Layer 7 load balancers)

While often the ingress controller in hosted k8s is fronted by their load balancer, it would be good to describe this in more detail (the distinction between layer 4 LB, an ingress controller and ingress controller on hosted k8s with possible additional needed resources to make that work)

We shouldn't copy paste any upstream docs, just in general explain what the most common options are regarding hosted k8s ingress also because we have a warning for EKS when creating a cluster but no corresponding docs explaining this.

**Comment by Tejeev** [comment]
I think we ran into this today as we were trying to figure out how to deploy an AWS ELB or ALB from the Rancher UI, and there doesn't appear to be an option to do so.  I think it would help to flesh out the docs in how we can deploy each type of LB, what Rancher will do in the background (create an ingress rule, or maybe actually deploy a Load Balancer using the cloud provider), and when and why certain options will or won't be available.

**Comment by Tejeev** [comment]
It turns out that L4 load balancers are created when deploying a workload
deploy a workload -> add a port -> select l4
This will create the ELB in AWS and wire it up internally to work.  I believe the functionality needs to be added to the LB page but until then, the docs should note how and where to do this.
I've opened these related issues: https://github.com/rancher/rancher/issues/25624 https://github.com/rancher/rancher/issues/25623

**Comment by NotoriousRebel** [comment]
any updates on this issue?
