### ISSUE TITLE
Expand architecture to reflect the functioning of an HA Rancher cluster

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#1699]
The architecture page (https://rancher.com/docs/rancher/v2.x/en/overview/architecture/) would benefit from having a section following the 1 node architecture that details the functioning of an HA cluster.  
How is traffic distributed between 3+ Rancher API Servers?  
How do they negotiate quorum? (the latter may belong in the HA docs)

I think it makes sense to have a diagram here and perhaps links to quick start guides somehow branching off here for each of the architectures described.

There are a lot of architectures deployed in customer environments and of course, we would probably only want to approach the most recommended install methods for single node and HA here.  I think we should slim down the installation docs that are scattered around in some way so that the alternative methods are mentioned but don't pose a confusion hazard, even for those that arrive at those pages by direct link from somewhere.  
Maybe offer a short blurp referencing the other different architecture options and links to relevant docs for them?

**Comment by catherineluse** [comment]
> we should slim down the installation docs 

The installation docs will eventually be somewhat rearranged so that the high availability installation is the default and the single node option is downplayed. 

I agree that it makes sense to have separate diagrams for the single node rancher server and a high availability Rancher server cluster. I think this diagram has played a part in misleading people to believe that the Rancher server can be part of a user cluster, so this change should clarify things.

The other architecture for Rancher is an air gap installation. You can install Rancher on a single node or high availability cluster in an air gapped environment, but realistically speaking, the same people that care about security/air gap would probably also care about high availability. So I can see another diagram being made for a high availability/air gap Rancher server cluster, but the single node/air gap configuration might be unnecessary.

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/1960
