### ISSUE TITLE
Clarify, fix bug, and enhancement on "volumes and storage" pages

### ISSUE THREAD

**Issue by cbron** [rancher/docs#1731]
Relates to: https://github.com/rancher/rancher/issues/22614

Page: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/volumes-and-storage/

Under "Adding storage classes", it says _"You must have storage provisioned"_. That is incorrect, when using a cloud provider, which we are in this case, storage classes dynamically create the storage in the cloud itself (like an ebs volume). Only in persistent volumes do you have to pre-provision. 

Under "Adding Persistent Volumes", the line _"You must have storage provisioned"_ is correct, but we should further clarify by saying something like _"Creating a persistent volume in rancher will not dynamically create a storage volume."_

It may further be helpful to add an example on the ["Provisioning Storage Examples"](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/volumes-and-storage/examples/) page for AWS. We could even show an example of doing it both ways: creating a PV and volume (and PVC) manually, and also creating a storage class and seeing the PVC and volume get generated dynamically.

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/2189.

I added AWS-specific instructions on creating persistent storage in the appropriate availability zone. I didn't add start-to-end AWS-specific instructions because I reorganized the storage docs to have two end-to-end tutorials: setting up existing storage, and dynamically provisioning new storage. I validated the steps on AWS with an EBS volume and found that both of the tutorials worked with AWS.
