### ISSUE TITLE
helm install command for cert-manager is missing name parameter for helm2

### ISSUE THREAD

**Issue by izaac** [rancher/docs#2116]
Following the instructions here for upgrading cert-manager
https://staging.rancher.com/docs/rancher/v2.x/en/installation/options/upgrading-cert-manager/

 I tried copy/pasting the following command (Step 4 install the new version of cert-manager):

```bash
$ helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v0.12.0 
```

**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
Follow the steps in the documentation using helm version 2

**Result:**

```bash
$ helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v0.12.0
Error: This command needs 1 argument: chart name
```

**Other details that may be helpful:**

I was able to do the install with the following command parameters:

```bash
$ helm install \
  --name cert-manager \
  --namespace cert-manager \
  --version v0.12.0 \
  jetstack/cert-manager
```

```
helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): 2.2.9
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported):  HA in AWS
- Machine type (cloud/VM/metal) and specifications (CPU/memory): cloud
- Kubernetes version (use `kubectl version`):

```
 v1.15.5
```

**Comment by catherineluse** [comment]
These are the Helm 3 commands, in which the name parameter was removed. There was a mixup where the Helm 3 commands got copied into the Helm 2 docs. I'll revert these back to the Helm 2 commands.

**Comment by catherineluse** [comment]
@izaac I tried to find the exact place in the documentation where the name parameter is missing. I couldn't find a step 4 where it said "Install the new version of cert manager." I did find a step 7 saying to install the new version of cert manager, where the name parameter is included:
<img width="996" alt="Screen Shot 2019-12-23 at 5 20 12 PM" src="https://user-images.githubusercontent.com/20599230/71386113-d797ba80-25a8-11ea-8f72-70cfce647c96.png">

I can see this command:
helm install --version 0.9.1 --name cert-manager --namespace kube-system jetstack/cert-manager

Should I just put it in multiple lines so that you don't have to scroll horizontally? Or am I looking in the wrong place?

Also, I think we're going to need Helm 3 commands for upgrading cert manager. I've made this issue to track it for now. https://github.com/rancher/docs/issues/2124

**Comment by catherineluse** [comment]
Oops,  I just realized that I was looking at the master branch, while you were looking at the staging branch.

I can see that @rawmind0 was the last person to edit those steps on the staging branch. I believe that what happened is that he changed the commands to remove the name parameter because the name parameter is not included in Helm 3.

I think what should happen is that in the staging branch, we should just add a note that says these steps assume you are using Helm 3, and if you are using Helm 2, you can refer to a copy of the original Helm 2 instructions. I can add that to the staging branch.

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/2125
