### ISSUE TITLE
Docs should refer to RKE by default.

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#2460]
Since is the primary product, I believe it makes sense to default to the RKE tab instead of the K3S one.
https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/kubernetes-rke/

**Comment by catherineluse** [comment]
Originally, the direction I got from Bill, Craig and Denise was that the K3s instructions should be default because K3s is an easier way to install Kubernetes for people who have never installed Kubernetes before, and because the architecture of K3s servers means that they can be treated as ephemeral.

On one hand, usually it's a good idea to write the docs in such a way that it reflects what the majority of users would want to do, and many users are still using RKE. But on the other hand, the docs also need to be written to decrease friction for less technical people who don't know what they are doing. The Rancher installation process is one of the most involved processes in our docs, and I see the default K3s option as a good move in the right direction to chip away at the complexity of installing Rancher for the first time. I think in this case, it is more important to make the docs less intimidating for newcomers than it is to reflect what the majority are doing. While I see reasonable points on both sides, I think K3s should remain the default.

**Comment by Tejeev** [comment]
Makes sense for the install process, but what about things that long time users often reference such as snapshotting and etc.  Perhaps a way to choose your tool of choice in one place at the top or bottom of the screen?

**Comment by Tejeev** [comment]
Actually I see they are separate now.. or was I looking at some other place in the docs when I opened this issue?  Either way, looks good and I like the new diagrams

**Comment by catherineluse** [comment]
Closing this issue because we removed the tabs for Rancher v2.5 because Rancher can now be installed on any K8s cluster.
