### ISSUE TITLE
Identical contents on different pages

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#2582]
Issue 1 :

- https://rancher.com/docs/rancher/v2.x/en/installation/options/helm2/rke-add-on/layer-4-lb/

- https://rancher.com/docs/rancher//v2.x/en/installation/options/rke-add-on/layer-4-lb/

These 2 pages have exactly the same content, is it really necessary to keep both of them on the website?

Issue 2:

- https://rancher.com/docs/rancher/v2.x/en/installation/options/helm2/rke-add-on/layer-7-lb/

- https://rancher.com/docs/rancher//v2.x/en/installation/options/rke-add-on/layer-7-lb/

These 2 pages have exactly the same content, is it really necessary to keep both of them on the website?

**Comment by catherineluse** [comment]
The RKE add-on docs are super old. When they were created, it wasn't yet possible to install Rancher with Helm.

Then the Helm 2 installation docs were created, but the RKE add-on installation docs were retained.

Then Helm 3 came out, and it had a breaking change with Helm 2. So the Helm 3 docs became default, but the Helm 2 docs had to be retained.

In both cases I believe the reason we retain those older docs is because we don't want to force enterprise customers to change the tools that they use.

You're right that those docs are redundant, but I think it's ok to leave them as-is because they aren't going to be updated. They are like archives of older docs.

**Comment by yzeng25** [comment]
OK, I will update it in the Chinese docs. Thanks!
