### ISSUE TITLE
[Monitoring] How to configure routes/ receivers and prometheus rules in UI

### ISSUE THREAD

**Issue by maggieliu** [rancher/docs#2830]
Need instructions on how to configure routes/ receivers and prometheus rules via UI

**Comment by maggieliu** [comment]
https://github.com/rancher/dashboard/issues/811
https://github.com/rancher/dashboard/issues/1238
https://github.com/rancher/dashboard/issues/1239

**Comment by bashofmann** [comment]
I started by extending the migration docs to show that you can add a Prometheus Rule through the UI: https://github.com/rancher/docs/pull/2832

**Comment by catherineluse** [comment]
I have added a rough draft of the docs for configuring routes, receivers and Prometheus rules to the staging branch.

The relevant docs are here:

- https://staging.rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/configuration/prometheusrules/
-  https://staging.rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/configuration/alertmanager

@aiyengar2 can you please review these pages?

**Comment by bashofmann** [comment]
These are great! The only small thing I found missing is explaining the annotations on an alert rule

![Bildschirmfoto 2020-12-07 um 14 09 26](https://user-images.githubusercontent.com/243056/101354794-ffedf700-3895-11eb-8071-b41d6ba4db95.png)

**Comment by catherineluse** [comment]
I've added the annotations to the configuration reference with this definition:

> Annotations are a set of informational labels that can be used to store longer additional information, such as alert descriptions or runbook links. A [runbook](https://docs.gitlab.com/ee/user/project/clusters/runbooks/) is a set of documentation about how to handle alerts. The annotation values can be [templated.](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#templating)

I found it hard to tell if "runbook" is a generic term, or a GitLab feature. Is it OK to link to the GitLab docs to define what a runbook is?

**Comment by bashofmann** [comment]
Runbook is a generic term: https://en.wikipedia.org/wiki/Runbook

**Comment by aiyengar2** [comment]
@catherineluse sorry for the late look, but here are my comments:
- nit: `About PrometheusRule Custom Resources` should be smaller. Seems too big compared to the original title.
- nit: `The PrometheusRules CRD defines a` -> `A PrometheusRule defines a`
- nit: `The PrometheusRule custom resource` -> `A PrometheusRule`

**Comment by aiyengar2** [comment]
@catherineluse sorry for the late look, but here are my comments:

https://staging.rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/configuration/prometheusrules/

- nit: `About PrometheusRule Custom Resources` should be smaller. Seems too big compared to the original title.
- nit: `The PrometheusRules CRD defines a` -> `A PrometheusRule defines a`
- `Prometheus rule files are held in PrometheusRule custom resources.` -> `For users who are familiar with Prometheus, a PrometheusRule contains the alerting and recording rules that you would normally place in a [Prometheus rule file](https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/).`
- nit: `The PrometheusRule custom resource defines a RuleGroup with your desired rules. Each specifies the following:` -> `A PrometheusRule allows you to define one or more RuleGroups. Each Rule Group consists of a set of alerting or recording rules with the following fields:`
- nit: `Alerting rules define alert conditions based on PromQL queries, and recording rules precompute frequently needed or computationally expensive queries at defined intervals.` -> remove the extra comma
- `A rule group may contain either alert rules or recording rules, but not both` -> `In Rancher's UI, we expect a rule group to contain either alert rules or recording rules, but not both`. (you could do this in Prometheus Operator)
- `Rancher v2.5.4 introduced the capability to configure reducers by filling out forms in the Rancher UI.`: should "reducers" be PrometheusRules or something else?
- `Wait to fire for` -> `Wait To Fire For`
- `Every evaluation cycle this is evaluated at the current time, ` for both Alerting and Recording rules should be `Prometheus will evaluate the current value of this PromQL expression on every evaluation cycle and `

https://staging.rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/configuration/alertmanager/

- Additional pre-requisite for using Receivers: `If you configured monitoring with an existing Alertmanager Secret, it must have a format that is supported by Rancher's UI, otherwise you will only be able to make changes based on modifying the Alertmanager Secret directly.`. Maybe also `We are continuing to make enhancements to what kinds of Alertmanager Configurations we can support using the Routes and Receivers UI, so please [file an issue](https://github.com/rancher/rancher/issues/new) if you have a request for a feature enhancement.`
- `Rancher v2.5.4 introduced the capability to configure reducers by filling out forms in the Rancher UI.` same question as above, is reducer a new terminology we're using? Maybe we should explain what we mean by reducers in some part of the docs if that is the case.
- Can't highlight any of the text in each of the Receiver boxes
- `Enable send resolved alerts` -> `Enable Send Resolved Alerts`
- For resolved alerts, the description can just be `Whether to send an follow-up notification if an alert has been resolved (e.g. [Resolved] High CPU Usage)`
- Pager Duty Integration Type values should be quoted to indicate those are the literal types you could select.
- `The Match field refers to a set of equality matchers an alert has to fulfill to match the node.` -> `The Match field refers to a set of equality matchers used to identify which alerts to send to a given Route based on labels defined on that alert.`, same for Match Regex
  - We should also probably add a section explaining how Routes are related to Rules, e.g. `When you define a Rule within a RuleGroup of a PrometheusRule, the spec of the Rule itself contains labels that are used by Prometheus to figure out which Route should receive this Alert. For example, an Alert with the label `team: front-end` will be sent to all Routes that match on that label.`

Additionally:
- Need to check for consistency of periods in all tables (e.g. all should have periods or none should)

Overall, this looks great! Thanks for writing this up :)

**Comment by catherineluse** [comment]
@aiyengar2 I've addressed your feedback in this commit. https://github.com/rancher/docs/commit/cab6c790aa0481265f548e367b2c6be4c3ba2a69

Good idea to say how PrometheusRules and Routes relate to each other. I added the paragraph to both the alertmanager doc and the prometheus rules doc because I figure it's relevant to both.

I don't know what part of my brain "reducer" came from. I meant to say "receiver" in one place and "PrometheusRule" in another.

I was able to highlight the text for the receivers on Chrome and Firefox. What browser are you using?

**Comment by aiyengar2** [comment]
Just left some notes on the commit.

> Good idea to say how PrometheusRules and Routes relate to each other. I added the paragraph to both the alertmanager doc and the prometheus rules doc because I figure it's relevant to both.

:+1:

> I don't know what part of my brain "reducer" came from. I meant to say "receiver" in one place and "PrometheusRule" in another.

😅 

> I was able to highlight the text for the receivers on Chrome and Firefox. What browser are you using?

Safari

**Comment by catherineluse** [comment]
I've made the suggested changes here: https://github.com/rancher/docs/commit/21f2e0f107dd1c8024d227f817eaa3aaf6c7a26f

The outstanding question is - is this requirement phrased all right, and is there a specific format required for the alertmanager secret in the Rancher UI?

> If you configured monitoring with an existing Alertmanager Secret, it must have a format that is supported by Rancher's UI. Otherwise you will only be able to make changes based on modifying the Alertmanager Secret directly. Note: We are continuing to make enhancements to what kinds of Alertmanager Configurations we can support using the Routes and Receivers UI, so please [file an issue](https://github.com/rancher/rancher/issues/new) if you have a request for a feature enhancement.

@deniseschannon @SheilaghM
