### ISSUE TITLE
[Rancher2] Missing option 2 on "Enable Istio in the Cluster" page.

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#2871]
**Request Summary:**
Missing option 2 on "Enable Istio in the Cluster" page.

**Details:**
1. URL: https://rancher.com/docs/rancher/v2.x/en/istio/v2.5/setup/enable-istio-in-cluster/#selectors-scrape-configs
2. Location: selectors-scrape-configs section
3. Description: listed options are option 1 and option 3, option 2 is missing. I doubt that there is actually only 2 options, since variable 'ingnoreNamspaceSelectors' is a boolean type, it has only 2 possible values: true or false. Besides this problem, the organization of this article can be improved as well.

![screenshot-rancher com-2020 11 25-11_26_47](https://user-images.githubusercontent.com/36651058/100179850-d3d78b00-2f11-11eb-9d5d-31c644b1e518.png)

**Comment by yzeng25** [comment]
Update: 
It seems like the description above is somewhat incorrect. After carefully reviewed the documentation yesterday, here is my suggestion on how to reorganize this part (and this is what I did in Rancher Chinese doc):

## Selectors & Scrape Configs

### The effect of ingnoreNamspaceSelectors parameter values on the monitoring range.
ingnoreNamspaceSelectors is a boolean type.
the default value of  ingnoreNamspaceSelectors is false.
when you set its value to true, you can monitor specific namespaces directly, or monitor  across namespaces with some twists.
when you set its value to false, you can monitor  across namespaces.
See sections below for detailed instruction.

### Set ingnoreNamspaceSelectors to True.

#### monitoring specific namespaces
// insert structions here
#### monitoring accross namespaces
// insert structions here
### Set ingnoreNamspaceSelectors to False
// insert structions here
#### Additional Scrape Config:
// insert structions here

**You can definitely try other structures, but I find structuring in this way works the best for Chinese users. Hope you can fix this soon, since the most recently published docs with this part is really confusing, it took me hours to figure out what is wrong, why is it wrong and how to restructure it. Thanks!**

**Comment by catherineluse** [comment]
This page became harder to read because there started to be a lot more options for Istio configuration. It starts to be so much information that it overwhelms the setup guide.

I think the best solution is to create a new section just for configuration options. I created a landing page for the config options that looks like this:

### Configuration Options

- Egress Support
- Enabling Automatic Sidecar Injection
- Overlay File
- Selectors and Scrape Configs
- Enable Istio with Pod Security Policies
- Additional Steps for Installing Istio on an RKE2 Cluster
- Additional Steps for Canal Network Plug-in with Project Network Isolation

## Egress Support
By default the Egress gateway is disabled, but can be enabled on install or upgrade through the values.yaml or via the overlay file.

## Enabling Automatic Sidecar Injection
Automatic sidecar injection is disabled by default. To enable this, set the sidecarInjectorWebhook.enableNamespacesByDefault=true in the values.yaml on install or upgrade. This automatically enables Istio sidecar injection into all new namespaces that are deployed.

## Overlay File
An Overlay File is designed to support extensive configuration of your Istio installation. It allows you to make changes to any values available in the IstioOperator API. This will ensure you can customize the default installation to fit any scenario.

The Overlay File will add configuration on top of the default installation that is provided from the Istio chart installation. This means you do not need to redefine the components that already defined for installation.

For more information on Overlay Files, refer to the Istio documentation.

## Selectors and Scrape Configs
The Monitoring app sets prometheus.prometheusSpec.ignoreNamespaceSelectors=false which enables monitoring across all namespaces by default. This ensures you can view traffic, metrics and graphs for resources deployed in a namespace with istio-injection=enabled label.

If you would like to limit Prometheus to specific namespaces, set prometheus.prometheusSpec.ignoreNamespaceSelectors=true. Once you do this, you will need to add additional configuration to continue to monitor your resources.

For details, refer to this section.

## Enable Istio with Pod Security Policies
Refer to this section.

## Additional Steps for Installing Istio on an RKE2 Cluster
Refer to this section.

## Additional Steps for Canal Network Plug-in with Project Network Isolation
Refer to this section.

**Comment by yzeng25** [comment]
Cool, thanks for the update.
