### ISSUE TITLE
[Rancher2]  Update AKS docs for AKSv2

### ISSUE THREAD

**Issue by cbron** [rancher/docs#3104]
Edit 5/12 (cmurphy): config reference should include which fields can be changed after the cluster is created

Epic GitHub issue: https://github.com/rancher/rancher/issues/31045
Points of contact: Michal Jura and Colleen

- [ ] Includes AKS permissions needed to create and update a cluster

**Comment by prabalsharma** [comment]
AKS cluster might take time (hours) to show up in `Cluster To register` list, based on region. We should mention this in our docs.

**Comment by catherineluse** [comment]
@mjura confirmed that the minimum AKS permissions are the same as what was required in v2.5, so no additional docs changes are needed.

**Comment by cbron** [comment]
@catherineluse we added a new section for EKSv2 / GKEv2 right, we would need to do the same here, permissions were just an additional thing to check. 
https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/#changes-in-rancher-v2-5

**Comment by catherineluse** [comment]
@cbron The new section is here https://staging.rancher.com/docs/rancher/v2.6/en/cluster-admin/editing-clusters/aks-config-reference/#changes-in-rancher-v2-6

It's just on a different page than before because we figured it would be better to reorganize the docs by putting the cluster configuration references under cluster administration instead of cluster provisioning. The cluster provisioning page still links to the same configuration docs.
