### ISSUE TITLE
[Rancher2]  Update GKE docs for GKEv2

### ISSUE THREAD

**Issue by cbron** [rancher/docs#3105]
Specifics Include:
* logs viewer permissions is needed
* How to use setting interval

Catherine edit April 23rd:
The same roles from the GKEv1 docs worked for GKEv2 as well, so the documented permissions won't change.

**Comment by catherineluse** [comment]
Point of contact: Colleen

**Comment by gaktive** [comment]
Once docs are in place, this will help with additional UI pointers: https://github.com/rancher/rancher/issues/32030

**Comment by catherineluse** [comment]
@btat I've added partial docs in staging to update the information about GKE cluster configuration.

The changes are in this PR https://github.com/rancher/docs/pull/3200 

- The new configuration reference page is at: https://staging.rancher.com/docs/rancher/v2.5/en/cluster-provisioning/hosted-kubernetes-clusters/gke/config-reference/ 
  - On this page I added a tab for v2.5.8 that explains the new cluster provisioning. It now says you need a project ID and it breaks out creating cloud credentials as a separate step.
- And the updated GKE cluster provisioning page is at: https://staging.rancher.com/docs/rancher/v2.5/en/cluster-provisioning/hosted-kubernetes-clusters/gke/ 
  - On this page I created a new GKE cluster configuration reference because it didn't already exist for Rancher before v2.5.8. So I created both tabs. I filled in the second half of the fields.   

Can you please create a new PR that fills in the incomplete information in the configuration reference? I've added placeholder section titles for the fields. (Or at least, I think I got all the fields. Let me know if you notice anything missing.)

There will also need to be changes to the docs regarding registered GKE clusters, but that's a different page and can be handled with a separate PR.

I've organized the configuration reference based on screenshots from GKE cluster provisioning before and after v2.5.8. This is how I got the organization to break down the reference options by cluster options, node pools etc.

# What still needs to be documented

- First half of configuration reference (the ones that I added placeholders for)
- Logs viewer permissions is needed
- How to use setting interval
- Registered cluster docs for GKE

# Screenshots of GKE provisioning in v2.5.8
<img width="1311" alt="Screen Shot 2021-04-14 at 8 38 43 AM" src="https://user-images.githubusercontent.com/20599230/115448903-16567880-a1cf-11eb-8949-fe6b54ef0086.png">
<img width="1317" alt="Screen Shot 2021-04-14 at 8 38 57 AM" src="https://user-images.githubusercontent.com/20599230/115448907-16ef0f00-a1cf-11eb-9d21-cdef0eedf3fa.png">
<img width="1302" alt="Screen Shot 2021-04-14 at 8 39 12 AM" src="https://user-images.githubusercontent.com/20599230/115448909-1787a580-a1cf-11eb-870d-ce945a730b4a.png">
<img width="1305" alt="Screen Shot 2021-04-14 at 8 39 20 AM" src="https://user-images.githubusercontent.com/20599230/115448915-18b8d280-a1cf-11eb-850e-c414f494afed.png">
<img width="1235" alt="Screen Shot 2021-04-14 at 8 39 43 AM" src="https://user-images.githubusercontent.com/20599230/115448916-19516900-a1cf-11eb-8391-3fa1c6ddafef.png">
<img width="498" alt="Screen Shot 2021-04-14 at 8 39 51 AM" src="https://user-images.githubusercontent.com/20599230/115448919-19516900-a1cf-11eb-87c6-976fcd410cdc.png">
<img width="1387" alt="Screen Shot 2021-04-14 at 8 39 58 AM" src="https://user-images.githubusercontent.com/20599230/115448921-19e9ff80-a1cf-11eb-97e5-575aca76272a.png">
<img width="1219" alt="Screen Shot 2021-04-14 at 8 40 07 AM" src="https://user-images.githubusercontent.com/20599230/115448924-1b1b2c80-a1cf-11eb-86c1-037edd4bd422.png">
<img width="1288" alt="Screen Shot 2021-04-14 at 8 43 01 AM" src="https://user-images.githubusercontent.com/20599230/115448926-1b1b2c80-a1cf-11eb-9fdf-e05fad0c125c.png">
<img width="1308" alt="Screen Shot 2021-04-14 at 8 37 13 AM" src="https://user-images.githubusercontent.com/20599230/115448895-148cb500-a1cf-11eb-8094-ce621dc2e82c.png">

# Screenshots from GKE provisioning before v2.5.8
<img width="1301" alt="Screen Shot 2021-04-14 at 9 06 26 AM" src="https://user-images.githubusercontent.com/20599230/115449038-35550a80-a1cf-11eb-9e49-baaafac91eb4.png">
<img width="1303" alt="Screen Shot 2021-04-14 at 9 06 13 AM" src="https://user-images.githubusercontent.com/20599230/115449042-36863780-a1cf-11eb-9413-12d3ab478fc8.png">
<img width="1295" alt="Screen Shot 2021-04-14 at 9 05 47 AM" src="https://user-images.githubusercontent.com/20599230/115449046-371ece00-a1cf-11eb-9cd0-35da9646c8b0.png">
<img width="1302" alt="Screen Shot 2021-04-14 at 9 04 44 AM" src="https://user-images.githubusercontent.com/20599230/115449048-37b76480-a1cf-11eb-9db8-b1521ecfe622.png">
<img width="1302" alt="Screen Shot 2021-04-14 at 9 00 26 AM" src="https://user-images.githubusercontent.com/20599230/115449054-384ffb00-a1cf-11eb-9a58-28519a788306.png">
<img width="1303" alt="Screen Shot 2021-04-14 at 9 00 16 AM" src="https://user-images.githubusercontent.com/20599230/115449057-38e89180-a1cf-11eb-910a-a60520c6b04e.png">
<img width="1294" alt="Screen Shot 2021-04-14 at 9 00 00 AM" src="https://user-images.githubusercontent.com/20599230/115449062-39812800-a1cf-11eb-91b3-38d61d52775a.png">
<img width="1324" alt="Screen Shot 2021-04-14 at 8 58 30 AM" src="https://user-images.githubusercontent.com/20599230/115449065-3ab25500-a1cf-11eb-96c1-d18c640a1a0d.png">
