### ISSUE TITLE
[Rancher2] Errors of updating different versions of the Rancher 2 documents

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#3171]
**Request Summary:**
Hi,

I think the recent updates of Rancher documents have some errors in it. Now Rancher documents have 3 different versions: **2.5** ,**2.0-2.4**, and **2.x**. 

2.5 and 2.0-2.4 are supposed to be the 'active' versions (e.g. all modification should be within these two versions), while the 2.x version is supposed to be the 'inactive' version (e.g. it is an archive, so modifications should not be in this version, just leave it as it is). 

During the recent document translation of Rancher documents, it seems like modifications are made both in **2.0-2.4**, and **2.x**, which does not make sense to me. 

My guess is modifications made in  **2.x** version were meant to be in **2.0-2.4** version instead. Yet there might be some miscommunications among engineers such that these modifications are made in different versions. 

**Details:**

1. https://github.com/rancher/docs/compare/0f45bd147dd3ea4b9961e463ce31780bd17ba486...master# From this link, we can see that changes are made in both **2.0-2.4** and **2.x** versions.
![image](https://user-images.githubusercontent.com/36651058/114029401-0b851500-98ac-11eb-92a4-feff619f99e4.png)

2. https://rancher.com/docs/rancher/v2.x/en/ and https://rancher.com/docs/rancher/v2.0-v2.4/en/ From these links, we can tell **2.x** is the archive version and **2.0-2.4** is the 'active' version.
![image](https://user-images.githubusercontent.com/36651058/114029221-df699400-98ab-11eb-95f1-2a517269c0dd.png)

![image](https://user-images.githubusercontent.com/36651058/114029089-c19c2f00-98ab-11eb-9a36-9692817ec8fa.png)

3. I consider an archive version as a 'leave-it-as-it-is' version, so it is isolated from all modifications. 
4. The only way you make modifications to both **2.0-2.4**, and **2.x** versions is to make the exactly same modifications to both versions. Otherwise it would not only create confusions for users, but it would also create huge versioning problems after some time.

**Comment by catherineluse** [comment]
I believe all the changes to the 2.x section have also been made to the 2.5 branch, so there's no cause for concern - yet. I don't think there are any changes that were made to 2.x that weren't also made to the versioned docs.

You're right that this is a problem. In the near future, what will help docs contributors is a notice at the top of every 2.x page that prevents people from thinking those are the latest docs. We've been having trouble getting it to show up on every page, but it should be up soon.

When SUSE does a brand refresh of the whole Rancher website, we're going to try to switch to a system where the product docs are separated from the rest of the website and from each other. This will allow us to use branches instead of directories, which we hope will be easier to maintain.

This current system is imperfect but hopefully it is temporary.
