### ISSUE TITLE
[K3s] converting existing cluster to etcd

### ISSUE THREAD

**Issue by bdols** [rancher/docs#3943]
**Request Summary:**
This section sounds like it's possible to keep pre-existing pods by adding the --cluster-init flag.
https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/#existing-clusters

However, this did not occur for me and I lost all pod state on the cluster that I wanted to turn into a multi-node cluster.

**Details:**
This needs more details on what "upgrading a cluster" entails. If it drops all existing pods, then state that.
Additionally, provide documentation or links to other documentation on how to check the sqlite database is valid.
This section sounds like it's a trivial operation.

**Comment by brandond** [comment]
On versions that support it, adding the `--cluster-init` flag on a server currently using sqlite does a one-time copy of all data from the sqlite datastore into etcd. There should be zero data loss and minimal downtime. If you're experiencing otherwise, please open an issue in the [k3s-io/k3s repo](https://github.com/k3s-io/k3s/issues/new?assignees=&labels=&template=bug_report.md&title=) describing your environment, how you added the CLI flag, and attach the logs from the first server startup after adding the flag.

**Comment by jtravee** [comment]
Hi @bdols, thank you for your contribution. I added a note in the docs to clarify the K3s versions necessary for successful migration to etcd.
