### ISSUE TITLE
[Rancher2] Fix Rancher 2.6.x upgrade documentation for older cert-manager versions

### ISSUE THREAD

**Issue by janeczku** [rancher/docs#4146]
https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/upgrades

The current documentation is:
1) *inconsistent* with regards to when `Option B` applies
2) instructs users to undertake a *re-installation* Rancher in order to upgrade cert-manager while there is a better, less intrusive process available

## Inconsistency regarding the versions of cert-manager for which `Option B` applies

First, the documentation states that `Option B` only applies to cert-manager versions older than 0.11.0.
> If you are also upgrading cert-manager to the latest version from a version older than 0.11.0, follow [Option B: Reinstalling Rancher and cert-manager.](https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/upgrades/#option-b-reinstalling-rancher-and-cert-manager)

But then it states that `Option B`  applies to cert-manager versions 1.5 and older:
> If you are currently running the cert-manager whose version is 1.5 or below, and want to upgrade both Rancher and cert-manager to a new version (1.6+ in the case of cert-manager), then you need to re-install both Rancher and cert-manager

## Document process to upgrade cert-manager that does not require a re-installation of Rancher

The current documented process (Option B) involves a Rancher re-installation and is thus unacceptable for many users with production environments. There is a better, less intrusive solution available which should be documented:

1. Install the cert-manager cli tool cmctl: https://cert-manager.io/docs/usage/cmctl/#installation
2. Run `cmctl upgrade migrate-api-version`  to ensure that all cert-manager CRs stored in etcd are v1 (https://cert-manager.io/docs/usage/cmctl/#migrate-api-version), see also: https://cert-manager.io/docs/installation/upgrading/upgrading-1.5-1.6/ and  https://cert-manager.io/docs/installation/upgrading/upgrading-1.6-1.7/
3. Upgrade cert-manager to 1.7.1 with a normal `helm upgrade`. You can go directly from 1.5 to 1.7
Then follow the Helm tutorial to update the API version of a release manifest: https://helm.sh/docs/topics/kubernetes_apis/#updating-api-versions-of-a-release-manifest release_name=rancher, release_namespace=cattle-system. In the decoded file search for `cert-manager.io/v1beta1`  and replace it with `cert-manager.io/v1`
4. Upgrade Rancher normally with `helm upgrade`

^^Thanks @bashofmann

**Comment by btat** [comment]
I believe the statement quoted about 1.5 was incorrectly added given the qualifying conditions for when Option B is applicable.

Earlier in the page
> If you are also upgrading cert-manager to the latest version from a version older than 0.11.0, follow [Option B: Reinstalling Rancher and cert-manager.](https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/upgrades/#option-b-reinstalling-rancher-and-cert-manager)
>
> Otherwise, follow [Option A: Upgrading Rancher.](https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/upgrades/#option-a-upgrading-rancher)

and the intro paragraph for Option B

> If you are also upgrading cert-manager to the latest version from a version older than 0.11.0, follow [Option B: Reinstalling Rancher and cert-manager.](https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/upgrades/#option-b-reinstalling-rancher-and-cert-manager)

But given that versions of cert-manager older than 0.11.0 are nearly 3 years old, it might make more sense to remove Option B from https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/upgrades instead.

There's also a page dedicated to [Upgrading Cert-Manager](https://rancher.com/docs/rancher/v2.6/en/installation/resources/upgrading-cert-manager/) already (which some other areas already point to). We could have that reviewed and where appropriate, replaced with the proposed process instead. 

Thoughts @janeczku @bashofmann @MbolotSuse ?

**Comment by bashofmann** [comment]
I think having the cert-manager upgrade instructions on its own page is a good idea. The Rancher upgrade page could then just link to this page.

But the cert-manager upgrade page is missing important details, especially on how to patch the Rancher installation so that the Rancher upgrade also works with the cert-manager api version changes. 
We really should not recommending uninstalling Rancher in order to do an upgrade, when there is a better option available.

**Comment by btat** [comment]
> @btat just to clarify: The intro paragraph for Option B actually reads:
> 
> > If you are currently running the cert-manager whose version is 1.5 or below, and want to upgrade both Rancher and cert-manager to a new version (1.6+ in the case of cert-manager), then you need to re-install both Rancher and cert-manager due to the API change in cert-manager 1.6

Sorry, forgot to mention that was the original intro for Option B before it was replaced by the text you quoted.

> But the cert-manager upgrade page is missing important details, especially on how to patch the Rancher installation so that the Rancher upgrade also works with the cert-manager api version changes.
We really should not recommending uninstalling Rancher in order to do an upgrade, when there is a better option available.

Just to confirm, the process above with `cmctl` is only for cases where there's an API change? 

For users upgrading between patch versions of cert-manager, does the current documented process [here](https://rancher.com/docs/rancher/v2.6/en/installation/resources/upgrading-cert-manager/#option-a-upgrade-cert-manager-with-internet-access) still apply?

**Comment by bashofmann** [comment]
Not really. If there is no API change on the cert-manager side, you just have to do a `helm upgrade`. By the way: the cert-manager v1 API was introduced and is unchanged since cert-manager 1.0. What happened in newer 1.x versions is that the deprecated alpha and beta API versions were removed.
We only have this big of a problem, because the Rancher Helm chart still used these deprecated APIs until recently.

**Comment by bashofmann** [comment]
Yes, patching the Rancher installation is mentioned in step 3 above:

> Then follow the Helm tutorial to update the API version of a release manifest: https://helm.sh/docs/topics/kubernetes_apis/#updating-api-versions-of-a-release-manifest release_name=rancher, release_namespace=cattle-system. In the decoded file search for cert-manager.io/v1beta1 and replace it with cert-manager.io/v1
