### ISSUE TITLE
Update Networking Default: Canal

### ISSUE THREAD

**Issue by MBishop17** [rancher/docs#524]

**Comment by kinarashah** [comment]
Starting 2.0.7, `Project Network Isolation` will be available under `Cluster Options` while creating/editing cluster. Currently this option is available only for RKE clusters having networking plugin as `canal`. When enabled, network policies are created to support project isolation. Similarly, when disabled, existing policies will be deleted and no new ones will be created. 

For clusters upgrading to 2.0.7 - 
- RKE Cluster + Canal 
Network policies would continue to work as they did before. (Exception: no project isolation for System Project) To disable network policies, you'd need to edit the cluster and disable it manually. 
- For all other clusters, no new network policies will be created; but existing network policies would still be present. In order to delete these existing policies, you can edit the cluster and disable network policies.
