### ISSUE TITLE
System Project

### ISSUE THREAD

**Issue by MBishop17** [rancher/docs#526]
- Provide High Level of System Project's purpose.
- Explain what its included namespaces are and how Rancher uses them to create and manage clusters.

**Comment by kinarashah** [comment]
When things aren't working as expected, users often check if containers in system namespaces are functioning properly. For example, looking at k8s networking, DNS containers which are part of `kube-system`. We introduce System Project as a collection of such important system namespaces so users can easily go and debug if something is wrong in UI. 

System Project is created automatically when a new cluster is added. By default, it'd have list of namespaces specified under `v3/settings/system-namespaces` if they exist. As with any other project, you can always add more namespaces to System Project or move namespaces between projects. Since it's crucial to working of the system, deleting system project isn't allowed from UI/API. 

Note - If you use RKE with networking plugin that supports project isolation(for instance, canal), it's important to note that no isolation would exist for system project. What this means? With project isolation on, you'd expect a namespace can only interact with namespaces that are within a same project. But, any namespace which is a part of system project will be able to communicate to all namespaces. This will also be applicable when you move namespaces between projects.
